In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
data=pd.read_csv('./vdjdb.txt',sep='\t', header=0)

data

complex.id gene                  cdr3       v.segm      j.segm  \
0               1  TRA         CIVRAPGRADMRF  TRAV26-1*01   TRAJ43*01   
1               1  TRB  CASSYLPGQGDHYSNQPQHF    TRBV13*01  TRBJ1-5*01   
2               0  TRB   CASSFEAGQGFFSNQPQHF    TRBV13*01  TRBJ1-5*01   
3               2  TRA        CAVPSGAGSYQLTF    TRAV20*01   TRAJ28*01   
4               2  TRB   CASSFEPGQGFYSNQPQHF    TRBV13*01  TRBJ1-5*01   
...           ...  ...                   ...          ...         ...   
92766       30592  TRB       CASSPGQGGDNEQFF   TRBV7-3*01  TRBJ2-1*01   
92767       30593  TRA          CAPQGATNKLIF  TRAV12-2*01   TRAJ32*01   
92768       30593  TRB       CASSLGAGGQETQYF   TRBV5-1*01  TRBJ2-5*01   
92769       30594  TRA        CLVGGSGGYNKLIF     TRAV4*01    TRAJ4*01   
92770       30594  TRB         CASSSTAQETQYF  TRBV11-2*01  TRBJ2-5*01   

           species           mhc.a           mhc.b mhc.class antigen.epitope  \
0      HomoSapiens        HLA-B*08             B2M      MHCI        FLKEKGGL   
1      HomoSapiens        HLA-B*08             B2M      MHCI        FLKEKGGL   
2      HomoSapiens        HLA-B*08             B2M      MHCI        FLKEKGGL   
3      HomoSapiens        HLA-B*08             B2M      MHCI        FLKEKGGL   
4      HomoSapiens        HLA-B*08             B2M      MHCI        FLKEKGGL   
...            ...             ...             ...       ...             ...   
92766  HomoSapiens  HLA-DQA1*05:01  HLA-DQB1*02:01     MHCII   PQQPFPQPEQPFP   
92767  HomoSapiens  HLA-DQA1*05:01  HLA-DQB1*02:01     MHCII   PQQPFPQPEQPFP   
92768  HomoSapiens  HLA-DQA1*05:01  HLA-DQB1*02:01     MHCII   PQQPFPQPEQPFP   
92769  HomoSapiens  HLA-DQA1*05:01  HLA-DQB1*02:01     MHCII   PQQPFPQPEQPFP   
92770  HomoSapiens  HLA-DQA1*05:01  HLA-DQB1*02:01     MHCII   PQQPFPQPEQPFP   

      antigen.gene antigen.species   reference.id  \
0              Nef           HIV-1  PMID:15596521   
1              Nef           HIV-1  PMID:15596521   
2              Nef           HIV-1  PMID:15596521   
3              Nef           HIV-1  PMID:15596521   
4              Nef           HIV-1  PMID:15596521   
...            ...             ...            ...   
92766       Gluten           Wheat  PMID:33927715   
92767       Gluten           Wheat  PMID:33927715   
92768       Gluten           Wheat  PMID:33927715   
92769       Gluten           Wheat  PMID:33927715   
92770       Gluten           Wheat  PMID:33927715   

                                                  method  \
0      {"frequency": "", "identification": "tetramer-...   
1      {"frequency": "", "identification": "tetramer-...   
2      {"frequency": "", "identification": "tetramer-...   
3      {"frequency": "", "identification": "tetramer-...   
4      {"frequency": "", "identification": "tetramer-...   
...                                                  ...   
92766  {"frequency": "", "identification": "tetramer-...   
92767  {"frequency": "", "identification": "tetramer-...   
92768  {"frequency": "", "identification": "tetramer-...   
92769  {"frequency": "", "identification": "tetramer-...   
92770  {"frequency": "", "identification": "tetramer-...   

                                                    meta  \
0      {"cell.subset": "CD8+", "clone.id": "", "donor...   
1      {"cell.subset": "CD8+", "clone.id": "", "donor...   
2      {"cell.subset": "CD8+", "clone.id": "", "donor...   
3      {"cell.subset": "CD8+", "clone.id": "", "donor...   
4      {"cell.subset": "CD8+", "clone.id": "", "donor...   
...                                                  ...   
92766  {"cell.subset": "CD4+", "clone.id": "", "donor...   
92767  {"cell.subset": "CD4+", "clone.id": "", "donor...   
92768  {"cell.subset": "CD4+", "clone.id": "", "donor...   
92769  {"cell.subset": "CD4+", "clone.id": "", "donor...   
92770  {"cell.subset": "CD4+", "clone.id": "", "donor...   

                                                 cdr3fix  vdjdb.score  \
0      {"cdr3": "

In [2]:
data.head

<bound method NDFrame.head of        complex.id gene                  cdr3       v.segm      j.segm  \
0               1  TRA         CIVRAPGRADMRF  TRAV26-1*01   TRAJ43*01   
1               1  TRB  CASSYLPGQGDHYSNQPQHF    TRBV13*01  TRBJ1-5*01   
2               0  TRB   CASSFEAGQGFFSNQPQHF    TRBV13*01  TRBJ1-5*01   
3               2  TRA        CAVPSGAGSYQLTF    TRAV20*01   TRAJ28*01   
4               2  TRB   CASSFEPGQGFYSNQPQHF    TRBV13*01  TRBJ1-5*01   
...           ...  ...                   ...          ...         ...   
92766       30592  TRB       CASSPGQGGDNEQFF   TRBV7-3*01  TRBJ2-1*01   
92767       30593  TRA          CAPQGATNKLIF  TRAV12-2*01   TRAJ32*01   
92768       30593  TRB       CASSLGAGGQETQYF   TRBV5-1*01  TRBJ2-5*01   
92769       30594  TRA        CLVGGSGGYNKLIF     TRAV4*01    TRAJ4*01   
92770       30594  TRB         CASSSTAQETQYF  TRBV11-2*01  TRBJ2-5*01   

           species           mhc.a           mhc.b mhc.class antigen.epitope  \
0      HomoSa

In [3]:
columns_to_drop = ['reference.id', 'method', 'meta','cdr3fix','web.method','web.method.seq','web.cdr3fix.nc','web.cdr3fix.unmp','mhc.a','mhc.b','mhc.class']
data.drop(columns=columns_to_drop, inplace=True)
data

complex.id gene                  cdr3       v.segm      j.segm  \
0               1  TRA         CIVRAPGRADMRF  TRAV26-1*01   TRAJ43*01   
1               1  TRB  CASSYLPGQGDHYSNQPQHF    TRBV13*01  TRBJ1-5*01   
2               0  TRB   CASSFEAGQGFFSNQPQHF    TRBV13*01  TRBJ1-5*01   
3               2  TRA        CAVPSGAGSYQLTF    TRAV20*01   TRAJ28*01   
4               2  TRB   CASSFEPGQGFYSNQPQHF    TRBV13*01  TRBJ1-5*01   
...           ...  ...                   ...          ...         ...   
92766       30592  TRB       CASSPGQGGDNEQFF   TRBV7-3*01  TRBJ2-1*01   
92767       30593  TRA          CAPQGATNKLIF  TRAV12-2*01   TRAJ32*01   
92768       30593  TRB       CASSLGAGGQETQYF   TRBV5-1*01  TRBJ2-5*01   
92769       30594  TRA        CLVGGSGGYNKLIF     TRAV4*01    TRAJ4*01   
92770       30594  TRB         CASSSTAQETQYF  TRBV11-2*01  TRBJ2-5*01   

           species antigen.epitope antigen.gene antigen.species  vdjdb.score  
0      HomoSapiens        FLKEKGGL          Nef           HIV-1            2  
1      HomoSapiens        FLKEKGGL          Nef           HIV-1            2  
2      HomoSapiens        FLKEKGGL          Nef           HIV-1            2  
3      HomoSapiens        FLKEKGGL          Nef           HIV-1            2  
4      HomoSapiens        FLKEKGGL          Nef           HIV-1            2  
...            ...             ...          ...             ...          ...  
92766  HomoSapiens   PQQPFPQPEQPFP       Gluten           Wheat            0  
92767  HomoSapiens   PQQPFPQPEQPFP       Gluten           Wheat            2  
92768  HomoSapiens   PQQPFPQPEQPFP       Gluten           Wheat            2  
92769  HomoSapiens   PQQPFPQPEQPFP       Gluten           Wheat            0  
92770  HomoSapiens   PQQPFPQPEQPFP       Gluten           Wheat            0  

[92771 rows x 10 columns]

In [4]:
# Filter by species
data_human = data[data['species'] == 'HomoSapiens']
data_mouse = data[data['species'] == 'MusMusculus']
data_monkey = data[data['species'] == 'MacacaMulatta'] 
#next analysis is for humans only
df=data_human
df

complex.id gene                  cdr3       v.segm      j.segm  \
0               1  TRA         CIVRAPGRADMRF  TRAV26-1*01   TRAJ43*01   
1               1  TRB  CASSYLPGQGDHYSNQPQHF    TRBV13*01  TRBJ1-5*01   
2               0  TRB   CASSFEAGQGFFSNQPQHF    TRBV13*01  TRBJ1-5*01   
3               2  TRA        CAVPSGAGSYQLTF    TRAV20*01   TRAJ28*01   
4               2  TRB   CASSFEPGQGFYSNQPQHF    TRBV13*01  TRBJ1-5*01   
...           ...  ...                   ...          ...         ...   
92766       30592  TRB       CASSPGQGGDNEQFF   TRBV7-3*01  TRBJ2-1*01   
92767       30593  TRA          CAPQGATNKLIF  TRAV12-2*01   TRAJ32*01   
92768       30593  TRB       CASSLGAGGQETQYF   TRBV5-1*01  TRBJ2-5*01   
92769       30594  TRA        CLVGGSGGYNKLIF     TRAV4*01    TRAJ4*01   
92770       30594  TRB         CASSSTAQETQYF  TRBV11-2*01  TRBJ2-5*01   

           species antigen.epitope antigen.gene antigen.species  vdjdb.score  
0      HomoSapiens        FLKEKGGL          Nef           HIV-1            2  
1      HomoSapiens        FLKEKGGL          Nef           HIV-1            2  
2      HomoSapiens        FLKEKGGL          Nef           HIV-1            2  
3      HomoSapiens        FLKEKGGL          Nef           HIV-1            2  
4      HomoSapiens        FLKEKGGL          Nef           HIV-1            2  
...            ...             ...          ...             ...          ...  
92766  HomoSapiens   PQQPFPQPEQPFP       Gluten           Wheat            0  
92767  HomoSapiens   PQQPFPQPEQPFP       Gluten           Wheat            2  
92768  HomoSapiens   PQQPFPQPEQPFP       Gluten           Wheat            2  
92769  HomoSapiens   PQQPFPQPEQPFP       Gluten           Wheat            0  
92770  HomoSapiens   PQQPFPQPEQPFP       Gluten           Wheat            0  

[85329 rows x 10 columns]

In [5]:
from tcrdist.repertoire import TCRrep
import pandas as pd
# 针对alpha链和beta链的数据进行筛选
data_alpha = df[df['gene'] == 'TRA'].copy()
data_beta = df[df['gene'] == 'TRB'].copy()
# 将数据列重命名以匹配TCRrep的期望格式
data_alpha.rename(columns={'cdr3': 'cdr3_a_aa', 'v.segm': 'v_a_gene', 'j.segm': 'j_a_gene'}, inplace=True)
data_beta.rename(columns={'cdr3': 'cdr3_b_aa', 'v.segm': 'v_b_gene', 'j.segm': 'j_b_gene'}, inplace=True)
data_alpha

complex.id gene       cdr3_a_aa         v_a_gene   j_a_gene  \
0               1  TRA   CIVRAPGRADMRF      TRAV26-1*01  TRAJ43*01   
3               2  TRA  CAVPSGAGSYQLTF        TRAV20*01  TRAJ28*01   
5               3  TRA     CAVKASGSRLT         TRAV2*01        NaN   
7               4  TRA   CAYRPPGTYKYIF  TRAV38-2/DV8*01  TRAJ40*01   
9               5  TRA   CIVRAPGRADMRF      TRAV26-1*01  TRAJ43*01   
...           ...  ...             ...              ...        ...   
92761       30590  TRA   CMDEGGSNYKLTF      TRAV26-1*01  TRAJ53*01   
92763       30591  TRA     CSLYNNNDMRF      TRAV26-1*01  TRAJ43*01   
92765       30592  TRA   CALSTDSWGKLQF         TRAV6*01  TRAJ24*01   
92767       30593  TRA    CAPQGATNKLIF      TRAV12-2*01  TRAJ32*01   
92769       30594  TRA  CLVGGSGGYNKLIF         TRAV4*01   TRAJ4*01   

           species antigen.epitope antigen.gene antigen.species  vdjdb.score  
0      HomoSapiens        FLKEKGGL          Nef           HIV-1            2  
3      HomoSapiens        FLKEKGGL          Nef           HIV-1            2  
5      HomoSapiens        FLKEKGGL          Nef           HIV-1            2  
7      HomoSapiens        FLKEKGGL          Nef           HIV-1            2  
9      HomoSapiens        FLKEQGGL          Nef           HIV-1            2  
...            ...             ...          ...             ...          ...  
92761  HomoSapiens    PQPELPYPQPQL       Gluten           Wheat            0  
92763  HomoSapiens    PQPELPYPQPQL       Gluten           Wheat            0  
92765  HomoSapiens   PQQPFPQPEQPFP       Gluten           Wheat            0  
92767  HomoSapiens   PQQPFPQPEQPFP       Gluten           Wheat            2  
92769  HomoSapiens   PQQPFPQPEQPFP       Gluten           Wheat            0  

[35643 rows x 10 columns]

In [6]:
#创造‘TCRrep’类
#alpha chain
data_alpha = pd.read_csv("cleaned_data_alpha.csv")
tr_alpha = TCRrep(cell_df=data_alpha, 
                  organism='human', 
                  chains=['alpha'], 
                  db_file='alphabeta_gammadelta_db.tsv')
tr_alpha.compute_distances()
print(tr_alpha.pw_alpha)

/Users/lulu/anaconda3/lib/python3.11/site-packages/tcrdist/repertoire.py:159: UserWarning: cell_df needs a counts column to track clonal number of frequency

  self._validate_cell_df()
/Users/lulu/anaconda3/lib/python3.11/site-packages/tcrdist/repertoire.py:791: UserWarning: No 'count' column provided; count column set to 1
  warnings.warn("No 'count' column provided; count column set to 1")
/Users/lulu/anaconda3/lib/python3.11/site-packages/tcrdist/repertoire.py:201: UserWarning: 

When TCRrep.<clone_df> size 34722 > 10,000.
	TCRrep.compute_distances() may be called explicitly by a user
	with knowledge of system memory availability.
	However, it's HIGHLY unlikely that you want to compute such
	a large numpy array. INSTEAD, if you want all pairwise distance,
	you will likely want to set an appropriate number of cpus with TCRrep.cpus = x,
	and then generate a scipy.sparse csr matrix of distances with:
	TCRrep.compute_sparse_rect_distances(radius=50, chunk_size=100), leaving df and df2 a

KeyboardInterrupt: 

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# 使用 seaborn 的 heatmap 函数来可视化距离矩阵
sns.heatmap(tr_alpha.pw_alpha)
plt.title("TCR Alpha Chain Pairwise Distance Matrix")
plt.show()

In [ ]:
import numpy as np
np.save('cleaned_data_alpha.npy', tr_alpha.pw_alpha)

下一步计算beta链

In [ ]:
#beta chain
tr_beta = TCRrep(cell_df=data_beta, 
                 organism='human', 
                 chains=['beta'], 
                 db_file='alphabeta_gammadelta_db.tsv')
tr_beta.compute_distances()
print(tr_beta.pw_beta)

In [ ]:
import numpy as np
np.save('tr_beta.pw_beta.npy', tr_beta.pw_beta )

下一步计算alpha，beta配对后的距离矩阵


In [7]:
data_beta1 = pd.read_csv("cleaned_data_beta.csv")
#beta chain
tr_beta1 = TCRrep(cell_df=data_beta1, 
                 organism='human', 
                 chains=['beta'], 
                 db_file='alphabeta_gammadelta_db.tsv')
tr_beta1.compute_distances()
print(tr_beta1.pw_beta)

/Users/lulu/anaconda3/lib/python3.11/site-packages/tcrdist/repertoire.py:159: UserWarning: cell_df needs a counts column to track clonal number of frequency

  self._validate_cell_df()
/Users/lulu/anaconda3/lib/python3.11/site-packages/tcrdist/repertoire.py:791: UserWarning: No 'count' column provided; count column set to 1
  warnings.warn("No 'count' column provided; count column set to 1")
/Users/lulu/anaconda3/lib/python3.11/site-packages/tcrdist/repertoire.py:201: UserWarning: 

When TCRrep.<clone_df> size 49549 > 10,000.
	TCRrep.compute_distances() may be called explicitly by a user
	with knowledge of system memory availability.
	However, it's HIGHLY unlikely that you want to compute such
	a large numpy array. INSTEAD, if you want all pairwise distance,
	you will likely want to set an appropriate number of cpus with TCRrep.cpus = x,
	and then generate a scipy.sparse csr matrix of distances with:
	TCRrep.compute_sparse_rect_distances(radius=50, chunk_size=100), leaving df and df2 a

[[  0  54  39 ... 197 177 199]
 [ 54   0  15 ... 185 153 178]
 [ 39  15   0 ... 185 165 187]
 ...
 [197 185 185 ...   0 104 131]
 [177 153 165 ... 104   0  95]
 [199 178 187 ... 131  95   0]]


In [8]:
import numpy as np
np.save('cleaned_data_beta.npy', tr_beta1.pw_beta)

In [ ]:
# 通过complex.id进行合并，假设每个complex.id对应一对alpha和beta链
# 确保complex.id不等于0
data_alpha = data_alpha[data_alpha['complex.id'] != 0]
data_beta = data_beta[data_beta['complex.id'] != 0]
# 合并alpha和beta链数据（拼接）
data_combined = pd.merge(data_alpha, data_beta, on='complex.id', suffixes=('_alpha', '_beta'))
data_combined['combined_feature'] = data_combined['cdr3_a_aa'] + "_" + data_combined['cdr3_b_aa']
data_combined

In [ ]:
data_combined = pd.read_csv("cleaned_data_combined.csv")
tr = TCRrep(cell_df = data_combined,
            organism = 'human', 
            chains = ['beta'],  # 这里chains参数是必须的，但因为我们用的是综合特征，所以实际选择哪个链并不重要
            db_file = 'alphabeta_gammadelta_db.tsv')
tr.compute_distances()
print(tr.pw_beta)

In [ ]:
import numpy as np
np.save('cleaned_data_combined.npy', tr.pw_beta)